### ISSUE TITLE
procrustesData

### ISSUE THREAD

**Issue by CarlijnB** [acorg/Racmacs#67] opened 2021-07-29 10:19 UTC
Hi Sam,
I'm trying out procrustesData on some maps, but get the following error:

procrustesData(map_1,map_2)
Error in ac_procrustes_map_data(map$optimizations[[optimization_number]],  : 
  mean(): object has no elements

Does procrustesMap need to have been run on these maps before?

When I tried procrustesData(map1,map1_v_map2)  [where the second map is the result of procrustesMap], I get results, but oddly I get distances out for sera despite the sera being different for map1 and map2 / there not being procrustes info about these in "map1_v_map2"

**Comment by shwilks** [comment] 2021-07-29 10:48
Hi Carlijn, for `procrustesData()` the intended usage is `procrustesData(map1, map2)` but I can see how the name is misleading.  Maybe I can think about some better documentation for that.

**Comment by CarlijnB** [comment] 2021-07-29 10:53
Hi Sam,
Thanks for getting back to me.
Yes I thought it was meant to be procrustesData(map1, map2) - hence why I'm reporting the error.
Is this a bug or am I missing something?

**Comment by shwilks** [comment] 2021-07-29 11:01
ah, sorry I hadn't read your error report properly.  I can't reproduce that error with my tests, what does it look like if you run `plot()` on map_1 and map_2 separately are they plotting ok?  Or perhaps there are no antigens or sera in the two maps with matching names between which to do the procrustes?

**Comment by CarlijnB** [comment] 2021-07-29 12:23
Hi Sam,
Thank you.
The situation is that the **antigens are the same**, but the **sera are different** (and thus have no matching names).
maps1 and map2 plot fine, and procrustesMap(map1, map2) works well for the antigens and (understandably) produces NAs for the sera.
Only procrustesData(map1,map2) gives that error.

**Comment by shwilks** [comment] 2022-03-01 11:07
Hi Carlijn, I think this should be fixed in the latest version, there is for example now a test included to check for the problem along the lines you're describing I think, 
```
test_that("Procrustes data with no matching sera", {

  mapA <- map1
  mapB <- map2
  srNames(mapB) <- paste("mismatch", srNames(mapB))
  expect_true("total_rmsd" %in% names(procrustesData(mapA, mapB)))

})
```
Please reopen if this hasn't addressed the problem though

**Closed by shwilks** 2022-03-01 11:07 UTC
