### ISSUE TITLE
"Error: Duplicate antigen names/IDs found." when using make.acmap

### ISSUE THREAD

**Issue by drserajames** [acorg/Racmacs#91] opened 2022-03-02 13:25 UTC
If the titre table does not have unique antigen names, then the output of `make.acmap` is 

```
Performing 100 optimizations
=======================================================================================
Optimization runs complete
Took 0.03 secs

Error: Duplicate sera names/IDs found.
```

Firstly, it would be more efficient for the error to occur before the optimisations (the user is especially sad if she's waited a long time for the map to optimise and then it throws an error)

Secondly, my desired behaviour for this situation would be one of the following
1. use the first antigen and drop the duplicates
2. use all antigens and rename the duplicates e.g. ANTIGEN 1 COPY 1, ANTIGEN 1 COPY 2
3. merge the antigens
And output a warning describing what has been done (with a merge report if relevant)
My personal preference would be 3, but I expect most people would want 1 or 2. 1 is what is currently used for VCM processing. It is important as CDC always titrate a duplicate antigen in every table as a control.
 
Also applies to serum names.

Not particularly high priority as the user can preprocess the data. Would be nice to switch the error message up to the top if possible.

**Comment by shwilks** [comment] 2022-03-09 10:31
hmm, I'm not able to reproduce this, do you have an example?

**Comment by drserajames** [comment] 2022-03-09 11:02
Sorry, it's `optimizeMap`, not `make.acmap`. The B/Vic table I sent you should give this error. I will double-check if not.

**Comment by shwilks** [comment] 2022-03-09 22:19
Sorry I wasn't able to reproduce it because it was only a problem when num_optimizations > 1 and for speed I had just tested on 1.  Anyway, should be fixed in v1.1.31

**Comment by drserajames** [comment] 2022-03-10 10:01
Thanks!

I'd prefer to have a warning that map contains duplicated antigen names/IDs.

**Comment by shwilks** [comment] 2022-03-10 11:27
Yes, we could have warning when an acmap is initially created that duplicate antigen ids or serum ids are found.

**Comment by shwilks** [comment] 2022-03-11 09:48
Now issues a warning in v1.1.33

**Closed by shwilks** 2022-03-11 09:48 UTC
