### ISSUE TITLE
Bootstrap point cloud not shown for 3d maps

### ISSUE THREAD

**Issue by antcart22** [acorg/Racmacs#82] opened 2022-02-09 16:22 UTC
Hi, 
I recently started using Racmacs. With Racmacs_1.1.18 bootstrapping works for 2d maps but not for 3d maps. Thoughts?

Thanks!

**Comment by davipatti** [comment] 2022-02-17 15:33
The issue is that bootstrap points are not being displayed in the viewer.

The call to `bootstrapMap` runs fine, (right?)

**Comment by shwilks** [comment] 2022-03-01 10:32
Thanks for reporting the issue! Hopefully this is now fixed in v1.1.27 but please reopen the issue if I'm mistaken

**Closed by shwilks** 2022-03-01 10:32 UTC
